language: python

before_script:
- pip install 'tox!=2.4.0,>=2.3'

script: tox

# Send notifications to #rpc-github in Slack
notifications:
  email: false
  slack:
    on_success: never
    on_failure: always
    secure: PMkX4ttSc5yaEKn1JYu1zf5SuE6kX0zoCv09wZI1npgYDqod72bxQBSWxYYre8/BCF9Te2UmuYIGtHxtNnvquwdfzHKJBEhpIcHJYWmBb1lNLC391stRPt2lePp5/kt/W2Ath1lhXoOZLIGZ4Akyj2S7alKlMWaqedApWOtBtQk=

matrix:
  include:
    - python: 2.7
      env: TOXENV=flake8
    - python: 2.7
      env: TOXENV=ansible-lint
    - python: 2.7
      env: TOXENV=releasenotes
    - python: 2.7
      env: TOXENV=bashate
    - python: 2.7
      env: TOXENV=release-script

sudo: false
