---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Run backup config
  hosts: localhost
  connection: local
  gather_facts: true
  tasks:
    - include: tasks/pre-backup-config.yml
  vars_files:
    - vars/upgrade-vars.yml
  tags:
    - backup


- name: Run backup and gather stats for galera
  hosts: galera_all[0]
  gather_facts: true
  tasks:
    - include: tasks/pre-backup-galera.yml
    - include: tasks/pre-gather-stats-galera.yml
  vars_files:
    - vars/upgrade-vars.yml
  tags:
    - galera


- name: Gather rabbitmq stats
  hosts: rabbitmq_all[0]
  gather_facts: true
  tasks:
    - include: tasks/pre-gather-stats-rabbitmq.yml
  vars_files:
    - vars/upgrade-vars.yml
  tags:
    - rabbitmq


- name: Gather utility stats
  hosts: utility_all[0]
  gather_facts: true
  tasks:
    - include: tasks/pre-gather-stats-utility.yml
  vars_files:
    - vars/upgrade-vars.yml
  tags:
    - utility


- name: Gather swift stats
  hosts: swift_proxy[0]
  gather_facts: true
  tasks:
    - include: tasks/pre-gather-swift-stats.yml
  vars_files:
    - vars/upgrade-vars.yml
  tags:
    - swift

- name: Perform log rotation and cleanup
  hosts: hosts
  gather_facts: true
  tasks:
    - include: tasks/pre-log-rotation.yml
  vars_files:
    - vars/upgrade-vars.yml
  tags:
    - hosts


- name: Perform log rotation and cleanup
  hosts: rsyslog_container
  gather_facts: true
  tasks:
    - include: tasks/pre-rsyslog.yml
  vars_files:
    - vars/upgrade-vars.yml
  tags:
    - rsyslog
